--liquibase formatted sql logicalFilePath:product-data-01.sql

--changeset GC:1
INSERT INTO CATEGORY(CATEGORY_NAME, DESCRIPTION) VALUES ('Phone', '...');
INSERT INTO CATEGORY(CATEGORY_NAME, DESCRIPTION) VALUES ('Desktop', '...');
INSERT INTO CATEGORY(CATEGORY_NAME, DESCRIPTION) VALUES ('Laptop', '...');
INSERT INTO CATEGORY(CATEGORY_NAME, DESCRIPTION) VALUES ('Tablet', '...');
INSERT INTO CATEGORY(CATEGORY_NAME, DESCRIPTION) VALUES ('Printer', '...');
INSERT INTO CATEGORY(CATEGORY_NAME, DESCRIPTION) VALUES ('Networking', '...');
INSERT INTO CATEGORY(CATEGORY_NAME, DESCRIPTION) VALUES ('Accessories', '...');